### ISSUE TITLE
Failed to fetch https://vxbakerxv.github.io/repo/ SSL -9836

### ISSUE THREAD

**Issue by mucke5** [vXBaKeRXv/vxbakerxv.github.io#2]
GitHub stopped supporting TLS 1.1 which is what Cydia uses, so your repo hosted on GitHub are not working right now.

Could you enable HTTP not HTTPS for the repo, I know it's not secure, but this is a temporal fix.

**Comment by vXBaKeRXv** [comment]
Thanks for the detailed info on the problem. Looks like abit of cydia repos don't use HTTPS. I'm not to sure where that option is, haven't looked yet. I will check it out 👊

**Comment by vXBaKeRXv** [comment]
Thanks for the detailed info and how to temp fix. 👍👍

Cant uncheck the option in settings...
HTTPS enforcement is required for GitHub Pages sites created after June 15, 2016 and using a github.io domain.
So, you have two solutions :
•find a github.io repository older than June 15, 2016
•set a custom domain name on your github.io

**Comment by MetalBreaker** [comment]
I'd suggest using GitLab.com Pages. It's easy and saved me a lot of headache... I'm hosting my own Cydia repo there. I tried Atlassian Web and GitHub Pages before that, and they were a pain. Just a recommendation!

**Comment by vXBaKeRXv** [comment]
Thanks! 👊

**Comment by 211this** [comment]
👌
